# Generated by Django 3.1.7 on 2021-04-08 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ManyToManyField(limit_choices_to=models.Q(_negated=True, id=2), related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
